feat: SYG-484 Integrate with Sygna Bridge
CoolBitX-Technology/transactid-library-java pull request #1
Opened 2021-01-18 08:43 UTC by kunmingLiu

2021-01-18 11:04 UTC, delbinwen commented on README.md
> +* Transfer data with a originator VASP in [Sygna Bridge][8]
suggest `data from originator VASP...`

2021-01-21 04:09 UTC, kunmingLiu commented on README.md
> +* Transfer data with a originator VASP in [Sygna Bridge][8]
fixed

2021-01-25 03:05 UTC, s60912frank requested changes
comment小修改

2021-01-25 03:05 UTC, s60912frank commented on src/main/java/com/netki/util/MessagesExtensions.kt
> + * Is valid, when it has one single primaryOwner.
* Validate if sygnaParameters is valid.
* It's valid when it has only one primaryOwner.

2021-01-25 03:11 UTC, kunmingLiu commented on src/main/java/com/netki/util/MessagesExtensions.kt
> + * Is valid, when it has one single primaryOwner.
fixed

2021-01-25 03:12 UTC, s60912frank approved these changes

2021-01-26 06:49 UTC, Dorac approved these changes

2021-01-27 02:04 UTC, merged